repos:
  - repo: local
    hooks:
      - id: flutter-analyze
        name: Flutter Analyze
        entry: flutter analyze
        language: system

      - id: flutter-test
        name: Flutter Test
        entry: flutter test
        language: system
