name: Build
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  flutter-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.35.7
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Build Android APK
        run: flutter build apk --debug
